server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: ""
          url-expression: "'lb://' + serviceId"
      routes:
        - id: listing-service-listings
          uri: lb://listing-service
          predicates:
            - Path=/api/listings/**
          filters:
            - RewritePath=/api/listings/(?<segment>.*), /api/listings/${segment}

        - id: listing-service-properties
          uri: lb://listing-service
          predicates:
            - Path=/api/properties/**
          filters:
            - RewritePath=/api/properties/(?<segment>.*), /api/properties/${segment}

        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/api/sales/**

        - id: rental-service
          uri: lb://rental-service
          predicates:
            - Path=/api/rentals/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/auth/**,/api/users/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.config: INFO
