server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: 
                - "http://localhost"
                - "http://localhost:5173"
                - "http://localhost:3000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: 
                - "Authorization"
                - "Content-Type"
                - "X-Requested-With"
                - "Accept"
                - "Origin"
                - "Access-Control-Request-Method"
                - "Access-Control-Request-Headers"
              exposedHeaders:
                - "Access-Control-Allow-Origin"
                - "Access-Control-Allow-Credentials"
              allowCredentials: true
              maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: listing-service
          uri: lb://listing-service
          predicates:
            - Path=/api/listings/**

        - id: sale-service
          uri: lb://sale-service
          predicates:
            - Path=/api/sales/**

        - id: rental-service
          uri: lb://rental-service
          predicates:
            - Path=/api/rentals/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/securities/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
    vn.proptech.gateway: DEBUG

security:
  jwt:
    secret: nBSIOJEfC4K+P1qYu3cR2MLxTvZg8kQhG7jWvU0mYlL9sZpA6oXxDnFeT7hWrVbS
