server:
  port: 8083

spring:
  application:
    name: payment-service

  # MongoDB configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/proptech_payment
      auto-index-creation: true

  # RabbitMQ configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

logging:
  level:
    root: INFO
    vn.proptech: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.amqp.rabbit: INFO

# Application specific properties
wallet:
  rabbitmq:
    exchange: proptech.wallet
    queues:
      wallet-created: wallet.created
      wallet-updated: wallet.updated
      wallet-deleted: wallet.deleted
    routing-keys:
      wallet-created: wallet.created
      wallet-updated: wallet.updated
      wallet-deleted: wallet.deleted

transaction:
  rabbitmq:
    exchange: proptech.transaction
    queues:
      transaction-created: transaction.created
      transaction-updated: transaction.updated
      transaction-deleted: transaction.deleted
    routing-keys:
      transaction-created: transaction.created
      transaction-updated: transaction.updated
      transaction-deleted: transaction.deleted