server:
  port: 8084

spring:
  application:
    name: sale-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongodb:27017/proptech_sale}
      auto-index-creation: true

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

logging:
  level:
    root: INFO
    vn.proptech: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.amqp.rabbit: INFO

# Application specific properties
contract:
  rabbitmq:
    exchange: proptech.contract
    queues:
      contract-created: contract.created
      contract-updated: contract.updated
      contract-deleted: contract.deleted
    routing-keys:
      contract-created: contract.created
      contract-updated: contract.updated
      contract-deleted: contract.deleted

transaction:
  rabbitmq:
    exchange: proptech.transaction
    queues:
      transaction-created: transaction.created
      transaction-updated: transaction.updated
      transaction-deleted: transaction.deleted
    routing-keys:
      transaction-created: transaction.created
      transaction-updated: transaction.updated
      transaction-deleted: transaction.deleted