global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-server:8888']

  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8761']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'listing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['listing-service:8081']

  - job_name: 'security-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['security-service:8082']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8083']

  - job_name: 'sales-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['sales-service:8084']

  - job_name: 'rental-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rental-service:8085']