spring:
  application:
    name: discovery-server
  config:
    import: "configserver:"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      username: configuser
      password: configpassword
      fail-fast: false
      retry:
        max-attempts: 10
        initial-interval: 3000
        max-interval: 10000
        multiplier: 2
      profile: ${SPRING_PROFILES_ACTIVE:local}